### ISSUE TITLE
API: Get elections by area (and/or postcode?)

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/EveryElection#1]
I made a slightly off-hand comment about this on slack, but thought it would be useful to formalise this a bit/start a discussion.

As a user, I would like to be able to query elections by making a call like:
https://elections.democracyclub.org.uk/api/elections/area/W06000001 or
https://elections.democracyclub.org.uk/api/elections/postcode/SW1A%201AA
(for example)

This should also be filterable by date in some way (i.e: it should be possible to construct an API call which returns a list of all elections where `poll_open_date > now()` or where `poll_open_date == '2017-05-04'`, etc).

This should return a list of election objects or an empty array `[]` if there are no upcoming elections for the given area.

This query should also be capable of determining elections which are relevant to a higher level of geography. For example, calling https://elections.democracyclub.org.uk/api/elections/area/E07000004 should return an array which contains an election object for `local.buckinghamshire.2017-05-04` (Aylesbury Vale being a child of Buckinghamshire) and any national elections + so on.

I think the first step on the road to this would be to make sure every organisation that an election can be associated with directly maps to an appropriate boundary in Mapit (some of them currently don't but could do e.g: Greater London Assembly, House of Commons). Some of them will/may require some additional importing (e.g: Police Force areas for Police and Crime Comissioner elections?). Having that will allow the codes returned by an applicable `covers` query to be referenced against the organisations in the DB to construct this output.

..that and actually having some elections to return :)

Also, woo - first issue!

**Comment by symroe** [comment]
Looking up elections by postcode is currently supported in YNR: 

https://candidates.democracyclub.org.uk/upcoming-elections?postcode=SW1A1AA

When we import elections from EE in to YNR, we'll be some way towards doing this.

The question is really about where the best place to do this is (I think EE is a more logical place than YNR), and how it should be done.

## How

At the moment YNR gets elections by asking a mapit install for the postcode endpoint. It then builds a list of area IDs (GSS codes, etc) and uses that list to query for `popolo.Post` objects with that ID. We can then go from `Post` to `Election`

https://github.com/mysociety/yournextrepresentative/blob/master/candidates/views/api.py#L27

This relies on a mapit install that holds all the geographies with the right code.

Where this gets tricky is when we have future boundaries that mapit doesn't know about. We could load them in to our own install of mapit, but [it doesn't know about start and end dates](https://github.com/mysociety/mapit/issues/277), so it would be hard to filter on dates properly. The generation system doesn't work well for this use case.

## Where

Because of this, I'm tempted to add the geography to EE directly. We could pull it in from mapit when it has them, or manually add them for future boundaries (we will likely get emailed them via an [FOI](https://www.whatdotheyknow.com/request/publish_new_boundary_shapefiles_2) or [rip them off a server](https://github.com/DemocracyClub/lgbce_boundary_scraper)).

This would allow us to do the point in polygon lookups in the same code base, meaning we don't have to rely on an external service being up.

I don't want to re-build mapit for no reason, but I think the regular future dated boundary issue might make it worth it.

Pinging @dracos about this too.

**Comment by chris48s** [comment]
> Looking up elections by postcode is currently supported in YNR:
> https://candidates.democracyclub.org.uk/upcoming-elections?postcode=SW1A1AA
> When we import elections from EE in to YNR, we'll be some way towards doing this.

From a short-term perspective, if that provides the necessary output to do something about https://github.com/DemocracyClub/UK-Polling-Stations/issues/431 by querying the EE data via YNR, that is probably good enough for now.

> I don't want to re-build mapit for no reason

Agreed. As well as the overhead associated with actually writing the code in the first place, you've also got to consider the additional overhead of data maintenance: It would be useful to avoid a situation where you don't have to update 2 different systems every time a new BoundaryLine release or whatever is available.

**Comment by dracos** [comment]
Whilst I agree dates would be nice, generations could potentially be used in some way, perhaps? You could create one or more inactive generations and put any future-dated boundaries in them (presumably you would want one generation per year, given boundaries change on election day). Then as each date occurs, you can make that inactive generation the active one and update the high generation of the other boundaries. You could create a one-to-one model to the Generation table to add a stat date for it, or something like that.

"This would allow us to do the point in polygon lookups in the same code base, meaning we don't have to rely on an external service being up." – you can also use the mapit code within this code as a python package if that's of use, though I guess fundamentally it's just a model holding some shapes :)

**Comment by chris48s** [comment]
On the start and end dates, presumably there isn't any valid situation where the end date of generation n isn't effectively implied by the start date of generation n+1?

**Comment by symroe** [comment]
We should define "mapit" here:

> you've also got to consider the additional overhead of data maintenance: It would be useful to avoid a situation where you have to update 2 different systems every time a new BoundaryLine release or whatever is available.

In this case, I think Chris is talking about `mapit.mysociety.org`, and that it would be annoying for us to duplicate the work of maintaining our own instances.

> you can also use the mapit code within this code as a python package if that's of use

And in this case Matthew is talking about `https://github.com/mysociety/mapit/`.

I think I mixed the two in my reply. I don't want to rewrite mapit the python package, but I can see us having to maintain our own mapit web service to meet our needs of having exact start and end dates.

As for working out the end date from the start date of the previous generation, I've done this as a bit of a bodge at the moment. I've also bodged the areas a bit. In legislation all the areas stop existing when the new areas come in, however mapit keeps the areas with the same name and gss across generations.

For example, 'Alvescot and Filkins' in West Oxfordshire was abolished on May the 4th 2016 and replaced with a new ward called 'Alvescot and Filkins'. The GSS reused the same code for this area, and mapit bumped the `generation_high` value for it.

In our use case we need to know that there was a change, so I've inferred this by looking at changes between generations and making a new set of divisions for each generation.

It's a hack, but it's good enough for now.

After thinking about this over the weekend I'm starting to think that we should just add a geography type to the division model and cache the shape directly in this code. It would make dealing with future boundaries easier, and it would save us from having to use mapit's generations in a way that they're not really designed for.

**Comment by dracos** [comment]
Umm, what makes you say Alvescot and Filkins was abolished in West Oxfordshire on 4th May 2016?

**Comment by dracos** [comment]
The boundaries in West Oxfordshire that changed at the May 2016 election were Hailey, Minster Lovell and Leafield; Charlbury and Finstock; Chadlington and Churchill. Each of those has a new GSS code and a start generation of 28 in mapit.mysociety.org.

**Comment by symroe** [comment]
Ah you're right, that was a bad example. There are cases where the Electoral Changes Order abolished all wards in a council and then remakes them with the same shape and name.

A better example would be [The Stroud (Electoral Changes) Order 2015](http://www.legislation.gov.uk/uksi/2015/2034/made)

> The existing wards of the district of Stroud are abolished.

In this case mapit (correctly) has different areas but a lot of the names are the same. In other cases where the Order changes a subset of the wards, the unchanged wards keep the same IDs.

Because I just want to get a full set of wards for a given date, I'm creating new objects for each set of wards created by an order, no matter if they are the same or not.

Maybe I shouldn't be doing this, but I don't have a reason to know that a ward was the same between sets (and I could always do this by looking at the mapit generations anyway)

**Comment by dracos** [comment]
Yes, if the existing wards are abolished, mapit.mysociety.org will create new areas (they'll have new GSS codes). I do occasionally wonder if we should have gone that way (bit late now!), but I'm not sure it has much bearing on what you want here, though? Unless I'm totally misunderstanding. As I said, if your installation of mapit had one generation per year, then whether you reimported identical boundaries each time or updated their generation as mapit.mysociety.org, you could query a particular generation to get the appropriate boundaries for that year.

**Comment by symroe** [comment]
Right, yes.

I didn't use mapit at first because we don't know the geographies of the areas until very close to elections (or even after). This approach allows me to do everything I need in order to make an election ID for an area without knowing the GSS code or the boundary – and I can add them later when we get them.

That's sort of why I'm thinking that adding the geography to the `OrganisationDivision` model in this code base is easier. For example, I ripped the boundaries from the LGBCE ArcGIS site here https://github.com/DemocracyClub/lgbce_boundary_scraper, but we don't have GSS codes for them yet. I could add them to a mapit install and hook them up to my models, or I could just add them to the model directly.

**Comment by symroe** [comment]
I _think_ this is done now

**Comment by chris48s** [comment]
So we've got query by postcode which mostly does the job for WhereDoIVote, excepting fuzziness around boundaries and postcodes which do occur in the `ResidentialAddress` model but don't return a result from mapit.. which we just deal with.

The other case (query by GSS code), we don't have (I think).

The specific use case I can think of for this right now is that I would like polling bot to be able to query say https://elections.democracyclub.org.uk/api/elections.json?gss=E07000181&future=1 and get back `local.oxfordshire.2017-05-04` and `local.west-oxfordshire.2017-05-04` so it can only notify us about data changes in areas with upcoming elections.

This isn't an urgent thing though. Also I could work around it by calling mapit to get an example postcode and then querying by postcode if necessary - so I could:
* call https://mapit.mysociety.org/area/E07000181.json (for example)
* parse out the `id`
* then call https://mapit.mysociety.org/area/2420/example_postcode.json (for example)
* use that to query Every Election
for each area. It is just not the most elegant solution.

Either way, this is not at all high priority. We can grab upcoming elections by postcode in WDIV which was the important use-case which this needed to address :)
