### ISSUE TITLE
By-election travails

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#1119]
Three (possibly related) issues in one!

1) A bunch of upcoming by-elections don't have seats contested or voting system info.

Compare https://whocanivotefor.co.uk/elections/local.chelmsford.writtle.by.2021-07-01/writtle/
with https://whocanivotefor.co.uk/elections/local.north-east-lincolnshire.heneage.by.2021-07-01/heneage/

2) uncontested by-elections. What should be displayed/ happen?

Compare https://whocanivotefor.co.uk/elections/local.caerphilly.aber-valley.by.2021-06-17/aber-valley/
with https://whocanivotefor.co.uk/elections/local.isles-of-scilly.2021-06-24/isles-of-scilly-local-election/

The first is on the front page of WCIVF, the second isn't even in candidates, I had to go via the WCIVF election page

3) Parliamentary by-elections lack the 'You will have one vote, and can choose from X candidates' line

Compare https://whocanivotefor.co.uk/elections/parl.chesham-and-amersham.by.2021-06-17/chesham-and-amersham/
with https://whocanivotefor.co.uk/elections/local.north-east-lincolnshire.heneage.by.2021-07-01/heneage/

**Comment by michaeljcollinsuk** [comment]
1. I am pretty confident this is due to missing voting system data due to cron job errors we have been getting recently. Working on a PR to update these crons which should help.

2. I think this is also related to the ballot importer failing due to cron errors - as after running the importer locally, they both display as cancelled/unconstested:
![Screenshot 2021-06-10 at 11 10 25](https://user-images.githubusercontent.com/15347726/121507472-91bcf500-c9dc-11eb-8e8a-9f294551da5a.png)
![Screenshot 2021-06-10 at 11 10 24](https://user-images.githubusercontent.com/15347726/121507483-92ee2200-c9dc-11eb-9cd5-bc9da4b9201f.png)

3. I've found a bug in WCIVF for this, will update
