### ISSUE TITLE
Whoops! when selecting parliamentary elections

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#1282]
Any UK parl. election selected from the front page of EE returns an error: https://elections.democracyclub.org.uk/elections/parl.2021-12-02/

Will says: "There's a whoops because I don't think that group exists."

**Comment by chris48s** [comment]
`parl.2019-12-02` doesn't exist
https://elections.democracyclub.org.uk/api/elections/parl.2019-12-02/

but `parl.2019-12-12` **does** exist
https://elections.democracyclub.org.uk/api/elections/parl.2019-12-12/
and
https://elections.democracyclub.org.uk/elections/parl.2019-12-12/
also throws an unhandled 500

In both cases its a bug. The one that does exist should work. A group that doesn't exist should throw a 404 like https://elections.democracyclub.org.uk/elections/local.2021-01-01/ does

**Comment by chris48s** [comment]
My hunch is this probably throws here
https://github.com/DemocracyClub/EveryElection/blob/19da682c2a1827d1c7017cf9a052237676dd0669/every_election/apps/elections/templates/elections/election_detail.html#L39
because a `parl.` group won't have any of these territory codes:
https://github.com/DemocracyClub/EveryElection/blob/d0f6d532116aa9c2254b0e4c28c039e759954721/every_election/apps/elections/models.py#L287-L292
