### ISSUE TITLE
The Vale of Glamorgan

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/EveryElection#1358]
Glamorgan appears to be the only council prefixed by 'the' in our IDs. Why?

**Comment by chris48s** [comment]
This is a decision inherited from the (now defunct) gov.uk registers. They assigned the councils short names but the process was a bit opaque and based on how the council preferred to be styled rather than according to a consistent style guide. It is also the reason why Lincoln elections are `local.city-of-lincoln...` but pretty much every other City council is just `local.leicester...` or `local.bristol...` or whatever.

I did enquire about this at the time, and I would normally link to the issue where they explained it, but it looks like when they archived https://github.com/openregister/local-authority-data they made the issues private so that's lost to the ether now :( Generating the slugs based off the gov.uk registers seemed like a reasonable-ish at the time. Obviously not so much now. It also makes continuing to follow this convention moving forwards impossible as structural change orders happen now because it was never based on any reproducible set of rules. It also makes it similarly hard to sensibly update the the [spec](https://elections.democracyclub.org.uk/reference_definition/), which still says use the register names.

**Comment by symroe** [comment]
[wiki](https://github.com/DemocracyClub/EveryElection/wiki/Managing-Organisations) page updated to suggest not using "the"
