### ISSUE TITLE
Better "election_title" for subtype elections

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#155]
On https://elections.democracyclub.org.uk/api/elections/naw.c.2018-02-06/ the "election_title" is `(Constituencies)`.

This should be…nicer. I'd say something like "Welsh assembly (Constituencies)" would do it.

**Comment by chris48s** [comment]
Had a quick look at this hoping it would be a one-liner but then realised that it is slightly more complicated than that.

The function for generating election titles generates bad titles or no titles at all for most group ids and never has done. For example, the election titles for `local.2016-05-05` and `mayor.2017-05-04` are `empty string`:
* https://elections.democracyclub.org.uk/api/elections/local.2016-05-05/
* https://elections.democracyclub.org.uk/api/elections/mayor.2017-05-04/

We've not really noticed this because we don't import these elections into YNR and we don't actually refer to elections by their title field through the front-end e.g:
* https://elections.democracyclub.org.uk/elections/local.2016-05-05/
* https://elections.democracyclub.org.uk/elections/mayor.2017-05-04/

I think in order to do this right, `ElectionBuilder.to_title()` needs a few slightly paths depending on what sort of group id/ballot id we're generating.
