### ISSUE TITLE
Remove cancelled election metadata

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/EveryElection#1685]
Ref https://github.com/DemocracyClub/WhoCanIVoteFor/pull/1390

1. With the change in logic in WCIVF, each case for uncontested & cancelled elections is accounted for. 
2. There will be outliers (it's not uncontested but it is a cancelled election) and in these cases, it's important to:
  a) not repeat the existing messages in WCIVF and 
  b) only add metadata in exceptional circumstances

- [ ] Remove the cancelled election metadata object https://github.com/DemocracyClub/aggregator-api/issues/369
- [x] Run a migration to remove historical metadata in WCIVF where the title == "Uncontested Election"
- [x] Add help text in EE to match 2 above

**Comment by chris48s** [comment]
WhoCanIVoteFor is not the only consumer of this data. If you remove it, WhereDoIVote will not be able to display info about cancelled and uncontested polls.

**Comment by symroe** [comment]
@chris48s You're right about uncontested elections, but since https://github.com/DemocracyClub/EveryElection/pull/426 we expose `cancelled` without any metadata being needed.

Metadata was designed as a flexible way to deal with _all the edge cases_. It's still useful for that, but we've learnt enough about uncontested polls now to know what we want to say and how we want to deal with them.

There's still a challenge in that YNR is the first DC product to know that a poll is uncontested: since https://github.com/DemocracyClub/yournextrepresentative/pull/1486 we calculate uncontested after the ballot is locked.

We need a way to feed this back into EE, and at the moment this happens manually by Peter adding an "uncontested" metadata object. This works...sort of, but what we really want is a boolean on the `Election` model he can set. 

This also means we can use metadata _in addition_ to uncontested elections, for example to add election specific context.

The check list above should also include "add `uncontested` to the election model in EE" to be complete, and then WDIV will need to pull that in too.

**Comment by chris48s** [comment]
Yes. If you're not going to consume it from `metadata`, then you will need to consume it from `$OTHER_PLACE`. Gotta get it from _somewhere_ though.

If you're going to change the way it is exposed in EE, as well as changing how EDIV consumes that it its own web app, you'll also need to consider how it is (re-)exposed via the WDIV API and the knock-on effect to the devs.DC API:

https://github.com/DemocracyClub/UK-Polling-Stations/blob/42dd95c23c128e9a2b8d3ac13281a6c35c78b2bf/polling_stations/apps/api/postcode.py#L110
https://github.com/DemocracyClub/aggregator-api/blob/5119d68a73425284bd709b2b0f26c2a1ec8fde5b/aggregator/apps/api/v1/stitcher.py#L73-L89
https://github.com/DemocracyClub/aggregator-api/blob/5119d68a73425284bd709b2b0f26c2a1ec8fde5b/aggregator/apps/api/v1/docs/notes.apibp#L59-L77

etc

**Comment by VirginiaDooley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remaining work Uncontested Elections](https://trello.com/c/wVdKWmvS/3214-remaining-work-uncontested-elections)
