### ISSUE TITLE
Offset in some local borough geodata

### ISSUE THREAD

**Issue by russss** [DemocracyClub/EveryElection#283]
After getting my boundary export code working, I've unfortunately noticed that a significant number of boundaries in EE are exhibiting what appears to be a constant offset of a few hundred metres.

![image](https://user-images.githubusercontent.com/45057/39808855-f8fa1cea-5377-11e8-9346-ca77a295953a.png)

The offset seems to mostly affect entire local authorities, and I've only verified it in the elections for 2018-05-03. A limited selection of affected areas are:

* Cherwell
* Rochford
* Watford Borough
* Winchester
* Welwyn Hatfield
* Merton **Abbey ward only**
* Sheffield
* Craven **Penyghent, Settle and Ribblebanks, and Hellifield and Long Preston wards only**
* Knowsley

This strikes me as rather a large offset to be caused by differences in CRS transformation.

**Comment by chris48s** [comment]
It has taken quite a while to get this sorted, but I've now _mostly_ fixed this.

There are still a few further issues around this topic:

* Some Northern Ireland boundaries still have issues, but these can't be corrected by importing from BoundaryLine because OS only covers GB. This spawns is a separate bucket of work around consuming open data from OSNI, which I've raised as #364
* There are 12 local gov wards which have had 'technical' boundary changes (i.e: where the division boundaries were changed but there was no Electoral Change Order). Some of these may still have issues and I haven't re-imported them. I need to do a bit of extra work to get those sorted (and work out how to deal with it in future). I've raised #278 to deal with those.
* The new County Electoral Divisions which were introduced prior to the 2016 local elections are still using boundaries imported from LGBCE's draft recommendations. We haven't back-ported the boundaries from BoundaryLine on to them because BoundaryLine doesn't (yet) have GSS codes for CEDs and we aren't able to assign them a reliable/stable identifier. I've raised #360 as a placeholder for this. I'll review it next when the October BL release appears. None of these should be _offset_ but some of them will probably not tessellate exactly in a layer with CED polygons sourced from BoundaryLine.

Other than the cases identified above which are now covered under more specific issues, this problem should be fixed (including for historic boundaries where we hold them) so I am going to close the issue. If you spot anything else, feel free to re-open (hopefully not! :crossed_fingers: ) Now that most of these issues are sorted, I've now gone back and re-generated all the election TopoJSON layers for all the historic elections back to 2015 and whacked them all in the S3 bucket. If you want to use those to check any known errors that previously existed, go for it.
